const pizzas = [
  {
    id: 1,
    name: "Napolitana",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    stock: 10,
    quantity: 0,
    price: 9.99,
    image: "",
  },
  {
    id: 2,
    name: "Margherita",
    ingredients: ["Tomato", "Mozzarella", "Garlic"],
    stock: 10,
    quantity: 0,
    price: 11.99,
    image: "",
  },
  {
    id: 3,
    name: "Quattro Formaggi",
    ingredients: ["Mozzarella", "Gorgonzola", "Parmesan"],
    stock: 10,
    quantity: 0,
    price: 12.99,
    image: "",
  },
  {
    id: 4,
    name: "Prosciutto e Funghi",
    ingredients: ["Prosciutto", "Mushrooms", "Mozzarella"],
    stock: 10,
    quantity: 0,
    price: 13.99,
    image: "",
  },
  {
    id: 5,
    name: "Diavola",
    ingredients: ["Spicy Salami", "Tomato", "Mozzarella"],
    stock: 10,
    quantity: 0,
    price: 14.99,
    image: "",
  },
  {
    id: 6,
    name: "Carbonara",
    ingredients: ["Bacon", "Egg", "Cream"],
    stock: 10,
    quantity: 0,
    price: 15.99,
    image: "",
  },
];
